build:
  version: "3.0"

loans:
  message: "Welcome to EazyBank loans related local APIs"
  contactDetails:
    name: "Paurav Singh - Developer"
    email: "paurav@eazybank.com"
  onCallSupport:
    - (123) 555-1234
    - (123) 523-1345

