services:
  accounts:
    image: "pauravsingh/accounts:s3"
    container_name: accounts-ms
    ports:
      - "8080:8080"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  loans:
    image: "pauravsingh/loans:s3"
    container_name: loans-ms
    ports:
      - "8090:8090"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
  cards:
    image: "pauravsingh/cards:s3"
    container_name: cards-ms
    ports:
      - "9000:9000"
    deploy:
      resources:
        limits:
          memory: 700m
    networks:
      - eazybank
networks:
  eazybank:
    driver: "bridge"

#Note: All microservices start at different ports, but what if there is dependency among these microservices.
#So to start all microservices on same network we define network tag and under that we provide network name.
#so now all our microservices start on same network and can communicate with each other.
